# Generated by Django 4.2.5 on 2023-10-06 10:02

from django.db import migrations, models
import django.db.models.deletion
import songbeats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Псевдоним автора')),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название трека')),
                ('audio', models.FileField(upload_to=songbeats.models.Beat.content_file_name, verbose_name='Файл с битом')),
                ('author', models.ManyToManyField(to='songbeats.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbeats.beat')),
            ],
        ),
    ]
