# Generated by Django 4.2.5 on 2023-10-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='author',
            field=models.ManyToManyField(to='songbeats.author', verbose_name='Автор(ы) трека'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbeats.beat', verbose_name='Выбраные треки'),
        ),
    ]
