# Generated by Django 4.2.5 on 2023-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0002_genre_genre_name_alter_beat_author_alter_genre_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='beat',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
