# Generated by Django 4.2.5 on 2023-10-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0003_author_slug_beat_slug_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='track',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='songbeats.beat', verbose_name='Выбраные треки'),
        ),
    ]
