# Generated by Django 4.2.5 on 2023-10-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0005_alter_genre_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='beat',
            field=models.ManyToManyField(to='songbeats.beat'),
        ),
    ]
