# Generated by Django 4.2.5 on 2023-10-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0006_remove_beat_author_author_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='beat',
            field=models.ManyToManyField(blank=True, to='songbeats.beat'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songbeats.beat', verbose_name='Выбраные треки'),
        ),
    ]
