# Generated by Django 4.2.5 on 2023-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0007_alter_author_beat_alter_genre_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='beat',
            field=models.ManyToManyField(blank=True, related_name='authors', to='songbeats.beat'),
        ),
    ]
