# Generated by Django 4.2.5 on 2023-10-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0008_alter_author_beat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='track',
        ),
        migrations.AddField(
            model_name='beat',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songbeats.genre', verbose_name='Жанр трека'),
        ),
    ]
