# Generated by Django 4.2.5 on 2023-10-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0009_remove_genre_track_beat_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='beat',
        ),
        migrations.AddField(
            model_name='beat',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songbeats.author', verbose_name='Исполнитель трека'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songbeats.genre', verbose_name='Жанр трека'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50, verbose_name='Название альбома')),
                ('cover', models.ImageField(blank=True, upload_to='', verbose_name='Обложка альбома')),
                ('slug', models.SlugField(default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songbeats.author', verbose_name='Автор альбома')),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songbeats.album', verbose_name='Альбом'),
        ),
    ]
