# Generated by Django 4.2.5 on 2023-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0011_remove_beat_author_beat_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='author',
            field=models.ManyToManyField(blank=True, to='songbeats.author', verbose_name='Исполнитель(исполнители) трека'),
        ),
    ]
