# Generated by Django 4.2.5 on 2023-10-09 11:55

from django.db import migrations, models
import songbeats.models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0012_alter_beat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='images/default-artist.jpg', upload_to=songbeats.models.Author.content_file_name),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to=songbeats.models.Album.content_file_name, verbose_name='Обложка альбома'),
        ),
    ]
