# Generated by Django 4.2.5 on 2023-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0013_author_image_alter_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на бит'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание жанра'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='beats', to='songbeats.author', verbose_name='Исполнитель(исполнители) трека'),
        ),
    ]
