# Generated by Django 4.2.5 on 2023-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0014_beat_url_genre_description_alter_beat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug_name',
            field=models.CharField(default='', max_length=50, verbose_name='Псевдоним автора slug'),
        ),
    ]
