# Generated by Django 4.2.5 on 2023-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0015_author_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug_name',
            field=models.CharField(max_length=50, verbose_name='Псевдоним автора slug'),
        ),
    ]
