# Generated by Django 4.2.5 on 2023-11-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0016_alter_author_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beats', to='songbeats.genre', verbose_name='Жанр трека'),
        ),
    ]
