# Generated by Django 4.2.5 on 2024-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0017_alter_beat_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Выкладывать?'),
        ),
        migrations.AddField(
            model_name='beat',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Выкладывать?'),
        ),
    ]
