# Generated by Django 4.2.5 on 2024-01-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songbeats', '0018_author_is_published_beat_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил?'),
        ),
        migrations.AddField(
            model_name='beat',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил?'),
        ),
    ]
