# Generated by Django 5.0.1 on 2024-01-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0019_author_added_by_beat_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug_name',
        ),
    ]
