# Generated by Django 5.0.1 on 2025-01-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0020_remove_author_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album', to='songbeats.author', verbose_name='Автор альбома'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название трека'),
        ),
    ]
