# Generated by Django 5.0.1 on 2025-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbeats', '0021_alter_album_author_alter_beat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название трека'),
        ),
    ]
