# Generated by Django 4.2.5 on 2023-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_to_add',
            field=models.BooleanField(default=True, verbose_name='Может ли добавлять треки?'),
        ),
    ]
